In [2]:
import numpy as np
from sklearn.impute import SimpleImputer


In [3]:
np.random.randint(1,10, size = (10,1))

array([[1],
       [4],
       [7],
       [2],
       [7],
       [6],
       [5],
       [8],
       [9],
       [1]])

In [4]:
arr = np.random.uniform(1,10, size = (1,2))
arr

array([[7.7254397 , 6.10717112]])

In [5]:
arr.reshape(2,1)

array([[7.7254397 ],
       [6.10717112]])

In [6]:
type(arr)

numpy.ndarray

In [7]:
arr = np.random.randint(1,10,size = (3,4))
arr

array([[1, 9, 9, 1],
       [5, 8, 7, 9],
       [8, 2, 3, 9]])

In [8]:
col = np.random.randint(3,10, size = (3,1))
arr2 = np.hstack((arr,col))
arr2

array([[1, 9, 9, 1, 7],
       [5, 8, 7, 9, 7],
       [8, 2, 3, 9, 8]])

row = np.vstack((arr,col))


In [9]:
row=np.random.randint(1,10,size=(1,4))
np.vstack((arr,row))

array([[1, 9, 9, 1],
       [5, 8, 7, 9],
       [8, 2, 3, 9],
       [2, 9, 7, 1]])

In [10]:
arr3 = np.random.randint(1,100, size = (20,3))
arr3

array([[69, 10, 18],
       [ 4, 10, 73],
       [64, 20, 21],
       [11,  2, 15],
       [52, 81, 81],
       [13, 41, 12],
       [36, 28, 96],
       [ 6, 88, 51],
       [17, 31, 96],
       [34, 51, 67],
       [ 2, 91, 13],
       [68, 39, 26],
       [ 1, 76, 60],
       [66, 59, 10],
       [75, 49, 23],
       [36, 96, 66],
       [76, 74, 76],
       [35, 13, 92],
       [57, 52, 59],
       [80, 95, 71]])

In [11]:
arr3[:10,:3]

array([[69, 10, 18],
       [ 4, 10, 73],
       [64, 20, 21],
       [11,  2, 15],
       [52, 81, 81],
       [13, 41, 12],
       [36, 28, 96],
       [ 6, 88, 51],
       [17, 31, 96],
       [34, 51, 67]])

In [12]:
arr[::2]

array([[1, 9, 9, 1],
       [8, 2, 3, 9]])

In [13]:
arr4 = np.random.randint(1,100, size = (100))
arr4


array([60, 88, 21, 59, 74, 23, 54, 80, 43, 83, 16, 87, 11, 50, 69, 46, 22,
       45, 99, 43, 97, 52, 17, 74, 68, 33, 30, 14, 55, 34, 15, 53, 80, 22,
       87, 16, 37, 94, 56,  9, 61, 88, 27,  3,  2, 37, 95, 53,  6, 51, 83,
       12, 24, 70, 39, 46, 72, 78, 31,  4, 65, 62, 51, 16, 61, 44,  8, 55,
        2, 69,  9, 91, 73, 63, 93, 98, 75, 92, 33, 71, 82, 99, 65, 75, 40,
       88, 36, 27, 78, 69, 73, 78, 64, 14, 47, 63, 18,  4, 90,  8])

In [14]:
arr4[20:81:3]

array([97, 74, 30, 34, 80, 16, 56, 88,  2, 53, 83, 70, 72,  4, 51, 44,  2,
       91, 93, 92, 82])

In [15]:
arr3[:1,:]

array([[69, 10, 18]])

In [16]:
#Data Importing
#CSV File, Images, JSONs

import pandas as pd
df = pd.read_csv(r'C:\Users\akw97\Desktop\Parami Courses\Advanced Machine Learning\IRIS.csv')

In [17]:
df[['species','sepal_length']]

species  sepal_length
0       Iris-setosa           5.1
1       Iris-setosa           4.9
2               NaN           4.7
3       Iris-setosa           4.6
4       Iris-setosa           5.0
..              ...           ...
145  Iris-virginica           6.7
146  Iris-virginica           6.3
147  Iris-virginica           6.5
148  Iris-virginica           6.2
149  Iris-virginica           5.9

[150 rows x 2 columns]

In [18]:
df.head()

sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          NaN           1.3          0.2          NaN
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          NaN  Iris-setosa

In [19]:
X =df.drop('species',axis = 1)
X

sepal_length  sepal_width  petal_length  petal_width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          NaN           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          NaN
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]

In [20]:
y = df['species']
y

0         Iris-setosa
1         Iris-setosa
2                 NaN
3         Iris-setosa
4         Iris-setosa
            ...      
145    Iris-virginica
146    Iris-virginica
147    Iris-virginica
148    Iris-virginica
149    Iris-virginica
Name: species, Length: 150, dtype: object

In [21]:
y =df.iloc[:,-1]
y

0         Iris-setosa
1         Iris-setosa
2                 NaN
3         Iris-setosa
4         Iris-setosa
            ...      
145    Iris-virginica
146    Iris-virginica
147    Iris-virginica
148    Iris-virginica
149    Iris-virginica
Name: species, Length: 150, dtype: object

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   149 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   149 non-null    float64
 4   species       149 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [23]:
df.isnull().sum()

sepal_length    0
sepal_width     1
petal_length    0
petal_width     1
species         1
dtype: int64

In [24]:
df['sepal_width'].fillna(df['sepal_width'].mean())

0      3.50000
1      3.00000
2      3.05302
3      3.10000
4      3.60000
        ...   
145    3.00000
146    2.50000
147    3.00000
148    3.40000
149    3.00000
Name: sepal_width, Length: 150, dtype: float64

Homework

std
mean
variance


SK learn imputers

In [25]:
print(df['sepal_length'].std())
print(df['sepal_length'].mean())
print(df['sepal_length'].var())

0.8280661279778629
5.843333333333334
0.6856935123042505


In [26]:
imp = SimpleImputer(strategy="mean")
df.iloc[:, :4] = imp.fit_transform(df.select_dtypes(exclude=["object"]))


imp2 = SimpleImputer(strategy="most_frequent")
df.iloc[:, 4:] = imp2.fit_transform(df.select_dtypes(include=["object"]))

In [27]:
imp = SimpleImputer(strategy="mean")
df_num = df.select_dtypes(exclude=["object"])
df[df_num.columns] = imp.fit_transform(df_num)

imp2 = SimpleImputer(strategy="most_frequent")
df_categorical = df.select_dtypes(include=["object"])  
df[df_categorical.columns] = imp2.fit_transform(df_categorical)



In [28]:
df.head()

sepal_length  sepal_width  petal_length  petal_width          species
0           5.1      3.50000           1.4     0.200000      Iris-setosa
1           4.9      3.00000           1.4     0.200000      Iris-setosa
2           4.7      3.05302           1.3     0.200000  Iris-versicolor
3           4.6      3.10000           1.5     0.200000      Iris-setosa
4           5.0      3.60000           1.4     1.205369      Iris-setosa

In [31]:
df[df['sepal_length']>1]

sepal_length  sepal_width  petal_length  petal_width          species
0             5.1      3.50000           1.4     0.200000      Iris-setosa
1             4.9      3.00000           1.4     0.200000      Iris-setosa
2             4.7      3.05302           1.3     0.200000  Iris-versicolor
3             4.6      3.10000           1.5     0.200000      Iris-setosa
4             5.0      3.60000           1.4     1.205369      Iris-setosa
..            ...          ...           ...          ...              ...
145           6.7      3.00000           5.2     2.300000   Iris-virginica
146           6.3      2.50000           5.0     1.900000   Iris-virginica
147           6.5      3.00000           5.2     2.000000   Iris-virginica
148           6.2      3.40000           5.4     2.300000   Iris-virginica
149           5.9      3.00000           5.1     1.800000   Iris-virginica

[150 rows x 5 columns]